base:
  train_pokemon_type: all

data_etl:
  external_data_path: 'data/external/'
  train_data_path: 'data/processed/pokemon'

train_lora:
  seed: 1337
  model_directory: 'models'
  base_model: 'runwayml/stable-diffusion-v1-5'
  lora_path: 'models/pkmnlora'
  learning_rate: 0.0001
  max_train_steps: 15000

generate_text_to_image:
  seed: 3000
  num_inference_steps: 35
  batch_size: 1
  batch_count: 20
  prompt: 'a pkmnlora pokemon'
  negative_prompt: ''
  output_directory: 'outputs'
  use_lora: True